language: python
jobs:
  include:
    # Linux: checkstyle and tests (with coverage)
    - name: "Python 3.6"
      python: 3.6
    - name: "Python 3.8"
      python: 3.8
install:
  - make build
  - pip install coveralls
script:
  - make checkstyle
  - make test-coverage
after_success:
  - coveralls
